// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_ADMIN.Models
{
    public partial class Ad
    {
        public int AdId { get; set; }
        public string Img { get; set; }
        public string Link { get; set; }
        public bool? ValIdity { get; set; }
    }
}