// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_ADMIN.Models
{
    public partial class Coupon
    {
        public Coupon()
        {
            MemberCoupon = new HashSet<MemberCoupon>();
        }

        public int CouponId { get; set; }
        public string Sn { get; set; }
        public int DiscountPrice { get; set; }
        public bool? ValIdity { get; set; }
        public string Name { get; set; }

        public virtual ICollection<MemberCoupon> MemberCoupon { get; set; }
    }
}