// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_ADMIN.Models
{
    public partial class FaviriteNews
    {
        public int FaviriteNewsId { get; set; }
        public int NewsId { get; set; }
        public int MemberId { get; set; }
        public bool? ValIdity { get; set; }

        public virtual Member Member { get; set; }
        public virtual News News { get; set; }
    }
}