// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_ADMIN.Models
{
    public partial class ForumReply2
    {
        public int ForumReply2Id { get; set; }
        public int ForumArticleId { get; set; }
        public int ForumReplyId { get; set; }
        public int MemberId { get; set; }
        public int ForumReplyFloor { get; set; }
        public int Floor { get; set; }
        public string ForumReply2Content { get; set; }
        public string Img { get; set; }
        public DateTime AddTime { get; set; }
        public bool? ValIdity { get; set; }
        public int LikeCount { get; set; }

        public virtual ForumReply ForumReply { get; set; }
        public virtual Member Member { get; set; }
    }
}