// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_ADMIN.Models
{
    public partial class Member
    {
        public Member()
        {
            BuyerBid = new HashSet<BuyerBid>();
            ContactAddProduct = new HashSet<ContactAddProduct>();
            FaviriteArticle = new HashSet<FaviriteArticle>();
            FaviriteNews = new HashSet<FaviriteNews>();
            FaviriteProduct = new HashSet<FaviriteProduct>();
            ForumArticle = new HashSet<ForumArticle>();
            ForumReply = new HashSet<ForumReply>();
            ForumReply2 = new HashSet<ForumReply2>();
            MemberCoupon = new HashSet<MemberCoupon>();
            SellerAddProduct = new HashSet<SellerAddProduct>();
        }

        public int MemberId { get; set; }
        public string NickName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string IdCardFront { get; set; }
        public string IdCardBack { get; set; }
        public string Access { get; set; }
        public bool? ValIdity { get; set; }
        public DateTime AddTime { get; set; }
        public string Name { get; set; }
        public int BuyerGrade { get; set; }
        public int SellerGrade { get; set; }
        public string BankCode { get; set; }
        public int? BankAccount { get; set; }
        public string CreditCard { get; set; }
        public string CreditCardDate { get; set; }
        public int? CreditCardCcv { get; set; }
        public string BillingAddress { get; set; }

        public virtual Bank BankCodeNavigation { get; set; }
        public virtual ICollection<BuyerBid> BuyerBid { get; set; }
        public virtual ICollection<ContactAddProduct> ContactAddProduct { get; set; }
        public virtual ICollection<FaviriteArticle> FaviriteArticle { get; set; }
        public virtual ICollection<FaviriteNews> FaviriteNews { get; set; }
        public virtual ICollection<FaviriteProduct> FaviriteProduct { get; set; }
        public virtual ICollection<ForumArticle> ForumArticle { get; set; }
        public virtual ICollection<ForumReply> ForumReply { get; set; }
        public virtual ICollection<ForumReply2> ForumReply2 { get; set; }
        public virtual ICollection<MemberCoupon> MemberCoupon { get; set; }
        public virtual ICollection<SellerAddProduct> SellerAddProduct { get; set; }
    }
}