// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_ADMIN.Models
{
    public partial class MemberCoupon
    {
        public int MemberCouponId { get; set; }
        public int CouponId { get; set; }
        public int MemberId { get; set; }
        public int Count { get; set; }

        public virtual Coupon Coupon { get; set; }
        public virtual Member Member { get; set; }
    }
}