// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_ADMIN.Models
{
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            ForumArticle = new HashSet<ForumArticle>();
            Product = new HashSet<Product>();
        }

        public int ProductCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string BrandName { get; set; }
        public string ProductName { get; set; }
        public string Img { get; set; }
        public bool? ValIdity { get; set; }

        public virtual ICollection<ForumArticle> ForumArticle { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}