// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_API.Models
{
    public partial class Banner
    {
        public int BannerId { get; set; }
        public string Img { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public bool? ValIdity { get; set; }
    }
}