// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_API.Models
{
    public partial class ContactAddProduct
    {
        public int Id { get; set; }
        public int? ProductId { get; set; }
        public int? BrandId { get; set; }
        public string Category { get; set; }
        public bool? ValIdity { get; set; }
        public int? MemberId { get; set; }

        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
    }
}