// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_API.Models
{
    public partial class NewsCategory
    {
        public NewsCategory()
        {
            News = new HashSet<News>();
        }

        public int NewsCategoryId { get; set; }
        public string CategoryName { get; set; }
        public bool? ValIdity { get; set; }

        public virtual ICollection<News> News { get; set; }
    }
}