// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIEG_API.Models
{
    public partial class Order
    {
        public int OrderId { get; set; }
        public int BuyerId { get; set; }
        public int? BuyerPrice { get; set; }
        public int ProductId { get; set; }
        public int? SellerId { get; set; }
        public int? SellerPrice { get; set; }
        public DateTime AddTime { get; set; }
        public DateTime? UpdateTime { get; set; }
        public DateTime? DoneTime { get; set; }
        public string State { get; set; }
        public string Pay { get; set; }
        public string Receiver { get; set; }
        public string ReceivingPhone { get; set; }
        public string ShippingAddress { get; set; }
        public bool? ValIdity { get; set; }

        public virtual Product Product { get; set; }
    }
}